[package]
name = "torrust-index"
readme = "README.md"
default-run = "main"

authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[workspace.package]
authors = ["Nautilus Cyberneering <info@nautilus-cyberneering.de>, Mick van Dijke <mick@dutchbits.nl>"]
categories = ["network-programming", "web-programming"]
description = "A BitTorrent Index"
documentation = "https://docs.rs/crate/torrust-tracker/"
edition = "2021"
homepage = "https://torrust.com/"
keywords = ["bittorrent", "file-sharing", "peer-to-peer", "torrent", "index"]
license = "AGPL-3.0-only"
publish = true
repository = "https://github.com/torrust/torrust-tracker"
rust-version = "1.72"
version = "3.0.0-alpha.1-develop"

[profile.dev.package.sqlx-macros]
opt-level = 3

[dependencies]
async-trait = "0"
futures = "0"
sqlx = { version = "0", features = [
    "runtime-tokio-native-tls",
    "sqlite",
    "mysql",
    "migrate",
    "time",
] }
config = "0"
toml = "0"
derive_more = "0"
serde = { version = "1", features = ["rc"] }
serde_derive = "1"
serde_json = "1"
serde_bencode = "0"
serde_bytes = "0"
urlencoding = "2"
argon2 = "0"
rand_core = { version = "0", features = ["std"] }
chrono = { version = "0", default-features = false, features = ["clock"] }
jsonwebtoken = "8"
sha-1 = "0"
reqwest = { version = "0", features = ["json", "multipart"] }
tokio = { version = "1", features = [
    "macros",
    "io-util",
    "net",
    "time",
    "rt-multi-thread",
    "fs",
    "sync",
    "signal",
] }
lettre = { version = "0", features = [
    "builder",
    "tokio1",
    "tokio1-rustls-tls",
    "tokio1-native-tls",
    "smtp-transport",
] }
sailfish = "0"
regex = "1"
pbkdf2 = { version = "0", features = ["simple"] }
text-colorizer = "1"
log = "0"
fern = "0"
bytes = "1"
text-to-png = "0"
indexmap = "1"
thiserror = "1"
binascii = "0"
axum = { version = "0", features = ["multipart"] }
hyper = "0"
tower-http = { version = "0", features = ["cors", "compression-full"] }
email_address = "0"
hex = "0"
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
rand = "0"
tempfile = "3"
uuid = { version = "1", features = ["v4"] }
which = "4"
