name: torrust
services:

  index:
    image: torrust-index-backend:debug
    entrypoint: torrust-index-backend
    tty: true
    environment:
      - TORRUST_INDEX_CONFIG=${TORRUST_INDEX_CONFIG}
      - TORRUST_INDEX_CORS_PERMISSIVE=true
      - CARGO_HOME=/home/appuser/.cargo
    networks:
      - server_side
    ports:
      - 3001:3001
    volumes:
      - ./lib/torrust:/var/lib/torrust
    depends_on:
      - tracker
      - mailcatcher
      - mysql

  tracker:
    image: torrust-tracker:debug
    entrypoint: torrust-tracker
    tty: true
    environment:
      - TORRUST_TRACKER_CONFIG=${TORRUST_TRACKER_CONFIG}
      - TORRUST_TRACKER_API_TOKEN=${TORRUST_TRACKER_API_TOKEN:-MyAccessToken}
    networks:
      - server_side
    ports:
      - 6969:6969/udp
      - 1212:1212/tcp
    volumes:
      - ./lib/torrust:/var/lib/torrust
    depends_on:
      - mysql

  mailcatcher:
    image: dockage/mailcatcher:0.8.2
    networks:
      - server_side
    ports:
      - 1080:1080
      - 1025:1025

  mysql:
    image: mysql:8.0
    command: '--default-authentication-plugin=mysql_native_password'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent'
        ]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root_secret_password
      - MYSQL_DATABASE=${TORRUST_INDEX_MYSQL_DATABASE:-torrust_index_backend_e2e_testing}
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_user_secret_password
    networks:
      - server_side
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  server_side: {}

volumes:
  mysql_data: {}
