version = "2"

[logging]
#threshold = "off"
#threshold = "error"
#threshold = "warn"
threshold = "info"
#threshold = "debug"
#threshold = "trace"

[database]
connect_url = "mysql://root:root_secret_password@mysql:3306/torrust_index"

[mail.smtp]
port = 1025
server = "mailcatcher"

