version = "2"

[logging]
#threshold = "off"
#threshold = "error"
#threshold = "warn"
threshold = "info"
#threshold = "debug"
#threshold = "trace"

[tracker]
api_url = "http://tracker:1212"
url = "udp://tracker:6969"

[database]
connect_url = "sqlite:///var/lib/torrust/index/database/e2e_testing_sqlite3.db?mode=rwc"

[mail.smtp]
port = 1025
server = "mailcatcher"
