[logging]
log_level = "info"

[tracker]
api_url = "http://tracker:1212"
url = "udp://tracker:6969"

[database]
connect_url = "mysql://root:root_secret_password@mysql:3306/torrust_index_e2e_testing"

[mail.smtp]
port = 1025
server = "mailcatcher"
