[metadata]
schema_version = "2.0.0"

[logging]
threshold = "info"

[core]
listed = false
private = false

[core.database]
driver = "sqlite3"
path = "/var/lib/torrust/tracker/database/e2e_testing_sqlite3.db"

[[http_trackers]]
bind_address = "0.0.0.0:7070"

[http_api]
bind_address = "0.0.0.0:1212"
