name: Container (Docker)

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always


jobs:
  test:
    name: Test Release
    runs-on: ubuntu-latest

    steps:
      - id: setup
        name: Setup Toolchain
        uses: docker/setup-buildx-action@v2
      
      - id: build_index
        name: Build
        uses: docker/build-push-action@v4
        with:
          push: false
          load: true
          target: release
          tags: torrust-index-backend:release
          cache-from: type=gha
          cache-to: type=gha,mode=max

  integration:
    name: Integration
    runs-on: ubuntu-latest

    steps:
      - id: checkout_index
        name: Checkout Repository (Index)
        uses: actions/checkout@v3

      - id: checkout_tracker
        name: Checkout Repository (Tracker)
        uses: actions/checkout@v3
        with:
          repository: torrust/torrust-tracker
          path: tracker

      - id: setup
        name: Setup Toolchain
        uses: docker/setup-buildx-action@v2

      - id: build_index
        name: Build (index)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          target: debug
          tags: torrust-index-backend:debug
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - id: build_tracker
        name: Build (tracker)
        uses: docker/build-push-action@v4
        with:
          context: tracker
          push: false
          load: true
          target: debug
          tags: torrust-tracker:debug
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - id: inspect_index
        name: Inspect (index)
        run: docker image inspect torrust-index-backend:debug

      - id: inspect_tracker
        name: Inspect (tracker)
        run: docker image inspect torrust-tracker:debug

      - id: compose
        name: Compose Applications
        run: docker compose build 

      - id: run
        name: Run Applications
        
        run: |
          export TORRUST_INDEX_CONFIG=$(cat index/config-index.mysql.local.toml)
          export TORRUST_TRACKER_CONFIG=$(cat index/config-tracker.local.toml)

          docker compose up --detach

      - id: check
        name: Check Applications
        run: docker ps
